let data;const $=s=>document.querySelector(s);
async function load(){data=await fetch("data/league.json?x="+Date.now()).then(r=>r.json());const saved=localStorage.getItem("eurolygos-admin-data");if(saved){try{data=JSON.parse(saved)}catch(e){}}render("home");startClock();$("#status").innerHTML="<strong>Privati lyga paruošta.</strong> <span>Po turo administratorius gali įkelti vadybininkų taškus.</span>"}
function round(){return data.rounds[0]}
function render(v){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$("#app").innerHTML=v==="home"?home():v==="standings"?standings():v==="schedule"?schedule():v==="results"?results():teams()}
function home(){return `<div class="grid"><section class="card"><div class="card-head"><div class="eyebrow">KITAS TURAS</div><h2>Rugsėjo 24–25 d.</h2></div>${round().pairings.map(game).join("")}</section>${standings()}</div>`}
function game(g){return `<div class="game"><div class="team">${g.homeTeam}<small>${g.homeManager}</small></div><div class="time">${g.time}<small>${g.date}</small></div><div class="team">${g.awayTeam}<small>${g.awayManager}</small></div></div>`}
function standings(){let rows=data.teams.map(t=>({...t,...(data.scores[t.manager]||{})})).sort((a,b)=>(b.pts||0)-(a.pts||0));return `<section class="card"><div class="card-head"><div class="eyebrow">BENDRA ĮSKAITA</div><h2>Turnyro lentelė</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Komanda</th><th>Vadybininkas</th><th>W</th><th>L</th><th>B</th><th>PTS</th></tr></thead><tbody>${rows.map((t,i)=>`<tr class="${i<6?"zone-playoff":i<10?"zone-playin":""}"><td>${i+1}</td><td><b>${t.team}</b></td><td>${t.manager}</td><td class="num">${t.w||0}</td><td class="num">${t.l||0}</td><td class="num">${t.b||0}</td><td class="num score">${t.pts||0}</td></tr>`).join("")}</tbody></table></div></section>`}
function schedule(){return `<section class="card"><div class="card-head"><div class="eyebrow">TVARKARAŠTIS</div><h2>Vadybininkų tarpusavio mačai</h2></div>${round().pairings.map((g,i)=>`<div class="result"><div><b>${i+1} mačas</b><br>${g.homeTeam} <span class="muted">(${g.homeManager})</span></div><b>VS</b><div>${g.awayTeam} <span class="muted">(${g.awayManager})</span></div></div>`).join("")}</section>`}
function results(){return `<section class="card"><div class="card-head"><div class="eyebrow">REZULTATAI</div><h2>1 turo rezultatai</h2></div>${round().pairings.map(g=>{let a=data.scores[g.homeManager]?.managerPoints,b=data.scores[g.awayManager]?.managerPoints;return `<div class="result"><div><b>${g.homeManager}</b><br><span class="muted">${g.homeTeam}</span></div><div class="pts">${a??"—"} : ${b??"—"}</div><div><b>${g.awayManager}</b><br><span class="muted">${g.awayTeam}</span></div></div>`}).join("")}</section>`}
function teams(){return `<section class="card"><div class="card-head"><div class="eyebrow">KOMANDOS</div><h2>20 vadybininkų</h2></div><div class="teamgrid">${data.teams.map(t=>`<div class="teamcard"><div class="logo">${t.code}</div><b>${t.team}</b><div class="muted">${t.manager}</div></div>`).join("")}</div></section>`}
function startClock(){let target=new Date(round().start+"T19:00:00+03:00");setInterval(()=>{let d=Math.max(0,target-new Date()),days=Math.floor(d/86400000),h=Math.floor(d/3600000)%24,m=Math.floor(d/60000)%60;$("#countdown").textContent=`${String(days).padStart(2,"0")} d. ${String(h).padStart(2,"0")} val. ${String(m).padStart(2,"0")} min.`},1000)}
function parsePoints(text){const out={};for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith("#"))continue;const m=line.match(/^(.+?)\s*[,;:\t]\s*(-?\d+(?:[.,]\d+)?)$/);if(m)out[m[1].trim()]=Number(m[2].replace(",","."));}return out}
function recalc(points){for(const t of data.teams){const s=data.scores[t.manager]||{w:0,l:0,b:0,pm:0,pts:0};s.managerPoints=points[t.manager]??s.managerPoints;data.scores[t.manager]=s}for(const g of round().pairings){const a=data.scores[g.homeManager],b=data.scores[g.awayManager];if(a.managerPoints==null||b.managerPoints==null)continue;if(a.managerPoints>b.managerPoints){a.w=(a.w||0)+1;b.l=(b.l||0)+1;a.pts=(a.pts||0)+3}else if(b.managerPoints>a.managerPoints){b.w=(b.w||0)+1;a.l=(a.l||0)+1;b.pts=(b.pts||0)+3}else{a.b=(a.b||0)+1;b.b=(b.b||0)+1}}localStorage.setItem("eurolygos-admin-data",JSON.stringify(data));render("standings")}
document.addEventListener("click",e=>{if(e.target.matches("nav button"))render(e.target.dataset.view);if(e.target.id==="adminBtn")$("#adminModal").hidden=false;if(e.target.id==="closeAdmin")$("#adminModal").hidden=true;if(e.target.id==="clearLocal"){localStorage.removeItem("eurolygos-admin-data");location.reload()}if(e.target.id==="applyPoints"){const points=parsePoints($("#pointsInput").value);if(!Object.keys(points).length){$("#adminHelp").textContent="Nerasta taškų. Naudokite formatą vadybininkas, taškai.";return}recalc(points);$("#adminHelp").textContent="Taškai pritaikyti šiame įrenginyje.";$("#adminModal").hidden=true}});$("#pointsFile").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>$("#pointsInput").value=r.result;r.readAsText(f)});load();